name: Create Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches: ["release", "test-workflow", "v2.0-build"]

jobs:
  # Release and linux
  builds-on-linux-and-release:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.11

      - name: Setup Poetry
        # You may pin to the exact commit or the version.
        # uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
